from helpers import enum

HackRfVendorRequest = enum(
    HACKRF_VENDOR_REQUEST_SET_TRANSCEIVER_MODE = 1,
    HACKRF_VENDOR_REQUEST_MAX2837_WRITE = 2,
    HACKRF_VENDOR_REQUEST_MAX2837_READ = 3,
    HACKRF_VENDOR_REQUEST_SI5351C_WRITE = 4,
    HACKRF_VENDOR_REQUEST_SI5351C_READ = 5,
    HACKRF_VENDOR_REQUEST_SAMPLE_RATE_SET = 6,
    HACKRF_VENDOR_REQUEST_BASEBAND_FILTER_BANDWIDTH_SET = 7,
    HACKRF_VENDOR_REQUEST_RFFC5071_WRITE = 8,
    HACKRF_VENDOR_REQUEST_RFFC5071_READ = 9,
    HACKRF_VENDOR_REQUEST_SPIFLASH_ERASE = 10,
    HACKRF_VENDOR_REQUEST_SPIFLASH_WRITE = 11,
    HACKRF_VENDOR_REQUEST_SPIFLASH_READ = 12,
    HACKRF_VENDOR_REQUEST_BOARD_ID_READ = 14,
    HACKRF_VENDOR_REQUEST_VERSION_STRING_READ = 15,
    HACKRF_VENDOR_REQUEST_SET_FREQ = 16,
    HACKRF_VENDOR_REQUEST_AMP_ENABLE = 17,
    HACKRF_VENDOR_REQUEST_BOARD_PARTID_SERIALNO_READ = 18,
    HACKRF_VENDOR_REQUEST_SET_LNA_GAIN = 19,
    HACKRF_VENDOR_REQUEST_SET_VGA_GAIN = 20,
    HACKRF_VENDOR_REQUEST_SET_TXVGA_GAIN = 21,
    HACKRF_VENDOR_REQUEST_ANTENNA_ENABLE = 23,
    HACKRF_VENDOR_REQUEST_SET_FREQ_EXPLICIT = 24,
    # USB_WCID_VENDOR_REQ = 25
    HACKRF_VENDOR_REQUEST_INIT_SWEEP = 26,
    HACKRF_VENDOR_REQUEST_OPERACAKE_GET_BOARDS = 27,
    HACKRF_VENDOR_REQUEST_OPERACAKE_SET_PORTS = 28,
    HACKRF_VENDOR_REQUEST_SET_HW_SYNC_MODE = 29,
    HACKRF_VENDOR_REQUEST_RESET = 30,
    HACKRF_VENDOR_REQUEST_OPERACAKE_SET_RANGES = 31,
    HACKRF_VENDOR_REQUEST_CLKOUT_ENABLE = 32,
    HACKRF_VENDOR_REQUEST_SPIFLASH_STATUS = 33,
    HACKRF_VENDOR_REQUEST_SPIFLASH_CLEAR_STATUS = 34,
)

HackRfConstants = enum(
    LIBUSB_ENDPOINT_IN=0x80,
    LIBUSB_ENDPOINT_OUT=0x00,
    HACKRF_DEVICE_OUT=0x40,
    HACKRF_DEVICE_IN=0xC0,
    HACKRF_USB_VID=0x1d50,
    HACKRF_USB_PID=0x6089)

HackRfError = enum(
    HACKRF_SUCCESS = 0,
    HACKRF_TRUE = 1,
    HACKRF_ERROR_INVALID_PARAM = -2,
    HACKRF_ERROR_NOT_FOUND = -5,
    HACKRF_ERROR_BUSY = -6,
    HACKRF_ERROR_NO_MEM = -11,
    HACKRF_ERROR_LIBUSB = -1000,
    HACKRF_ERROR_THREAD = -1001,
    HACKRF_ERROR_STREAMING_THREAD_ERR = -1002,
    HACKRF_ERROR_STREAMING_STOPPED = -1003,
    HACKRF_ERROR_STREAMING_EXIT_CALLED = -1004,
    HACKRF_ERROR_USB_API_VERSION = -1005,
    HACKRF_ERROR_NOT_LAST_DEVICE = -2000,
    HACKRF_ERROR_OTHER = -9999,
    # Python defaults to returning none
    HACKRF_ERROR=None
)

HackRfTranscieverMode = enum(
    HACKRF_TRANSCEIVER_MODE_OFF = 0,
    HACKRF_TRANSCEIVER_MODE_RECEIVE = 1,
    HACKRF_TRANSCEIVER_MODE_TRANSMIT = 2,
    HACKRF_TRANSCEIVER_MODE_SS = 3,
    TRANSCEIVER_MODE_CPLD_UPDATE = 4,
)

